### ISSUE TITLE
Teleporting

### ISSUE THREAD

**Issue by chadalen** [chadalen/astraeus#36]
Currently there is no way to teleport. Will need to implement one along with the teleport command.

**Comment by IanWONeill** [comment]
I saw this Issue and thaught, damn he's right theres no way to teleport, basically for the command i wrote this simple file, i dont know if :

@SubscribesTo(CommandEvent.class)
public final class TeleportCommands extends Command {

	private int x, y, z;

	@Override
	protected boolean execute(Player player, CommandParser parser) {
		if (parser.hasNext(3)) {
			x = parser.nextInt();
			y = parser.nextInt();
			z = parser.nextInt();

			player.setPosition(new Position(x, y, z));

			return true;
		} else if (parser.hasNext(2)) {
			x = parser.nextInt();
			y = parser.nextInt();

			player.setPosition(new Position(x, y));

		}
		/**
		 * TODO eventually add TeleTo and TeleToMe for administrators to get to
		 * players locations.
		 */
		return false;
	}

	@Override
	public boolean test(CommandEvent event) {
		return event.getName().equalsIgnoreCase("tele");
	}

	@Override
	protected PlayerRights rights() {
		return PlayerRights.DEVELOPER;
	}

}


Though when i try to teleport the client (the official one now) throws this error:
Exception in thread "Thread-3" java.lang.ArrayIndexOutOfBoundsException: -30
	at com.runescape.Client.setCameraLocation(Client.java:9936)
	at com.runescape.Client.moveCameraWithPlayer(Client.java:12995)
	at com.runescape.Client.drawGameScreen(Client.java:8662)
	at com.runescape.Client.processDrawing(Client.java:9549)
	at com.runescape.GameApplet.run(GameApplet.java:192)
	at com.runescape.Client.run(Client.java:5356)
	at java.lang.Thread.run(Unknown Source)

odd right? for different locations it will throw a different number, for example

Exception in thread "Thread-3" java.lang.ArrayIndexOutOfBoundsException: 261
	at com.runescape.Client.setCameraLocation(Client.java:9936)
	at com.runescape.Client.moveCameraWithPlayer(Client.java:12995)
	at com.runescape.Client.drawGameScreen(Client.java:8662)
	at com.runescape.Client.processDrawing(Client.java:9549)
	at com.runescape.GameApplet.run(GameApplet.java:192)
	at com.runescape.Client.run(Client.java:5356)
	at java.lang.Thread.run(Unknown Source)

when you login though you are in the area you wanted to go to.

**Comment by IanWONeill** [comment]
EDIT: ive just realized that this command is teleporting everything else, i used ::tele x y z and eveything moved upstairs haha.

**Comment by IanWONeill** [comment]
Problem is with this, Npcs Follow you? Asin try it and switch heigh level, the Npcs will move too.
